fieldLayouts:
  2fdecf00-d83e-437b-89fd-1fdde53dc919:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 5bda1bff-b811-47a7-9cd8-a621caefd2c8 # Area
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a70f443e-c410-42b2-bf16-787a374b518d # Image Overlay Title
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d72415e0-6aed-4abd-8168-1a280232aed2 # Image
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 89a26fef-5211-426b-a4e4-664a86902217 # Description
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'List About'
        sortOrder: 1
handle: aboutList
hasTitleField: true
name: 'About List'
section: 55c0d7ad-80d9-42a8-be17-c37bdf832d28 # About People
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
