fieldLayouts:
  72ebb6df-2a31-4cbd-a083-71bf5834b22e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: __blank__
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 063d332e-4f40-4a64-83fe-173a66d9f468
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a3dfacbf-4480-40d5-8f9f-7eea466f5305 # Funding Priorities Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f12b861b-1433-4812-8a43-ba80ee2ee16b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a1080ad-3c8a-458d-a731-198b32431f10 # Funding Priorities Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bb39044-70b6-4ad6-85cd-ae9ece97da06
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c45ef764-6d87-4d6a-a7a1-9a8cfbd9eae7 # Funding Priorities Quote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2044a453-4f5d-47af-a379-0ee9f54f19bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b3f42d73-e532-4113-84d9-dcd339afb373 # Funding Priorities Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91f6dc71-0d17-46e8-89fe-aeffd5d398bc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b246f6f5-aae4-4ccf-8873-79fec03eb560 # Show on Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7637d7f-b493-41ee-b1b5-9e99b2533594
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6d627c8a-630d-4493-9fd8-26705ee0c9d8
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: 4d43fd40-00af-462c-8195-298bb85a7403 # Funding Priorities 
sortOrder: 1
titleFormat: '{fundingTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
