fieldLayouts:
  e8190990-dfae-4fc2-8e27-c7c3bf4d69e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 44847c5d-f2ea-4888-bccf-9c50b108320f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 678241bf-b17d-4ac2-86db-01677b85b493 # Grant page Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7049e725-ea70-441b-80ca-199821c8dadd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2e8045b6-f7ff-443a-af0c-4e44c8b212eb # Gratee Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7b0e981-7016-4e6b-99c7-dec5b1a3532b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7cc790a0-42c6-48cc-93a9-9bfa9c369dd1 # Grant Details
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd7f32c5-1318-4412-aa19-be98fd229b66
            userCondition: null
            warning: null
            width: 100
        name: Grantees
        uid: ac03e557-88ec-41a0-ad79-b83ebc1faa20
        userCondition: null
handle: grantees
hasTitleField: true
name: Grantees
section: c32f4690-71c7-4850-a667-c5d8ce9509be # Grantees
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
