fieldLayouts:
  e8190990-dfae-4fc2-8e27-c7c3bf4d69e2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: a0df5825-d799-4f4b-b5ae-79ea22477a30 # Funding Priorities
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2bce50ce-2855-4389-a096-7cccfe880c42 # Grant Year
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ae12584b-abf7-40a0-8f34-a2472b88c366 # Grant Page Thumb
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 81e38d81-b9c3-4565-9dca-c4667f889c35 # Grant Popup Header
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e8f4a024-13a0-4624-96ba-5a2411beee6a # Grant Popup Logo
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ca74696d-15a8-4dc5-921e-3c466eca86a5 # Blurb
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7cc790a0-42c6-48cc-93a9-9bfa9c369dd1 # Grant Details
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Grantees
        sortOrder: 1
handle: grantees
hasTitleField: true
name: Grantees
section: c32f4690-71c7-4850-a667-c5d8ce9509be # Grantees
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
