fieldLayouts:
  06aaa9dd-67a3-45f3-b540-8486851b38ab:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e37f9da1-5daf-4282-9758-6ef2cc1a7ed0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 43d06bce-50fa-46b4-ae2c-12ce9d9e3f4d # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb70f82c-af30-44d7-99b5-8d4786aa6ad1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8088684e-ac0d-4a9a-b60d-baf541e9ce03 # Top Image Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91720b6a-2e95-4334-853d-f3d8b076e738
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5283a77f-4c1f-4c96-8b3f-2ad6cbfaaeb0 # Top Image Caption
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c08caac-3d80-485c-b0b4-ef90498ba85e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e4faeaa9-19a9-417a-a8b3-a379a7fb691e # Top Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b6730ce-4d96-452f-81d6-e5c6a7dce5e5
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: 1118db5f-9f9a-40d2-8b6e-824fc04c7e20
        userCondition: null
handle: homepage
hasTitleField: true
name: Homepage
section: b4e85528-fab4-4546-9dcb-58f9c190ca68 # Homepage
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
