fieldLayouts:
  2f3b5b62-1aa9-48a6-aa48-f4abbaffef13:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 9d9c344a-9077-451c-bbe4-b84cc2f4bef6 # Quote
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 47e80725-1930-4612-aacb-7856439acab4 # Quote Attribution
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Quotes
        sortOrder: 1
handle: quotes
hasTitleField: false
name: Quotes
section: 05cd4c32-7f1c-43bf-af56-246502778d15 # Quotes
sortOrder: 1
titleFormat: '{quoteAttribution}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
