defaultPlacement: end
fieldLayouts:
  034516fd-c477-4cba-87d6-e47fc7aeae96:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: newsResourcesCategory
name: 'News & Resources Category'
siteSettings:
  665742c3-51bb-4c48-8153-aef194693ac4: # Stolte Family Foundation (en-US)
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: e6e6503a-ff2f-449a-b5c7-339952b704b0
