columnSuffix: null
contentColumnType: string
fieldGroup: 78ea7dd1-bc0b-419e-8460-2b07daa26eea # Grantees
handle: blurb
instructions: ''
name: Blurb
searchable: true
settings:
  byteLimit: null
  charLimit: '150'
  code: false
  columnType: string
  initialRows: '3'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
