columnSuffix: null
contentColumnType: string
fieldGroup: c8433762-3bbd-435b-ba87-6993de142681 # News & Resources
handle: category
instructions: ''
name: Category
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: '3'
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'group:647043aa-d631-42fc-ab2a-7dd8116c1933' # News & Resources Category
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
