columnSuffix: null
contentColumnType: text
fieldGroup: ab97eced-2c66-43df-8866-f5604d148745 # Config
handle: defaultMetaDescription
instructions: ''
name: 'Default Meta Description'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
