columnSuffix: null
contentColumnType: string
fieldGroup: 78ea7dd1-bc0b-419e-8460-2b07daa26eea # Grantees
handle: fundingCategory
instructions: null
name: 'Funding Category'
searchable: true
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Education
        -
          - value
          - education
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Climate
        -
          - value
          - climate
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Civic Engagement'
        -
          - value
          - civic-engagement
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
