columnSuffix: null
contentColumnType: text
fieldGroup: ab97eced-2c66-43df-8866-f5604d148745 # Config
handle: metaBodyCode
instructions: 'JS, CSS, or analytics to paste right after the opening body tag'
name: 'Meta Body Code'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '10'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
