columnSuffix: null
contentColumnType: smallint(4)
fieldGroup: ab97eced-2c66-43df-8866-f5604d148745 # Config
handle: oldestGrantYear
instructions: 'The oldest grant year to display (ex: 2015, 2016, etc)'
name: 'Oldest Grant Year'
searchable: true
settings:
  decimals: 0
  defaultValue: null
  max: 2050
  min: 2010
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
