columnSuffix: null
contentColumnType: text
fieldGroup: 5b17fe86-1473-47bf-b671-672f9b069b28 # Quotes
handle: quoteAttribution
instructions: ''
name: 'Quote Attribution'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
