columnSuffix: null
contentColumnType: string
fieldGroup: e80763fb-469b-4bda-bc61-60a9494e30b8 # Social Media SEO
handle: seoDescription
instructions: 'If not blank, this will override the meta description for social media SEO purposes'
name: 'SEO Description'
searchable: true
settings:
  byteLimit: null
  charLimit: '160'
  code: false
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
