columnSuffix: null
contentColumnType: text
fieldGroup: 78ea7dd1-bc0b-419e-8460-2b07daa26eea # Grantees
handle: yearsFunded
instructions: 'Ex : Funded Since 2021, Funded 2017 - 2019'
name: 'Years Funded'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
