defaultPlacement: end
enableVersioning: true
handle: aboutList
name: 'About People'
propagationMethod: all
siteSettings:
  665742c3-51bb-4c48-8153-aef194693ac4: # Stolte Family Foundation (en-US)
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: e7066ff5-f9ae-4629-9bc5-aa835071a87d
type: structure
